# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'HaidoraQRScanningView' do
pod 'ZXingObjC', '~> 3.0.0'
end

target 'HaidoraQRScanningViewTests' do
pod 'ZXingObjC', '~> 3.0.0'

end

